### ISSUE TITLE
Manual `measurement` dependency must now be specified when installing on Python 2.x

### ISSUE THREAD

**Issue by BigglesZX** [coddingtonbear/django-measurement#90]
Just a note that [`measurement`](https://github.com/coddingtonbear/python-measurement) has now published version 3.0.0 which drops support for Python 2.x. That library is referenced as a dependency of `django-measurement` using the specification `measurement>=1.6`. This means that in Python 2.x environments installation of `django-measurement` will now fail, since `measurement` 3.0.0 will be selected, and 3.0.0 includes a dependency on a version of `sphinx` that requires Python >=3.5 for installation.

A workaround I found for this is to add **`measurement<3.0.0`** to your `requirements.txt` or `setup.py` file in addition to `django-measurement`. This ensures the 2.x-compatible version of `measurement` is resolved as a dependency when installing `django-measurement`.

Hope that helps someone else running into this issue. Thanks for a great package!

**Comment by codingjoe** [comment]
@BigglesZX thanks for the info. In fact both packages are maintained by me, so I was aware of the discontinued Python 2 support. Just for the record, this packages also no longer officially supports Python 2.

Since we are at it, I must highly encourage you to upgrade to Python 3. Python 2 reaches end of life in December.
